### ISSUE TITLE
Please help me please please

### ISSUE THREAD

**Issue by voobl** [mmcloughlin/finsky#5]
Traceback (most recent call last):
  File "/usr/bin/finsky", line 9, in <module>
    load_entry_point('finsky==0.3.3', 'console_scripts', 'finsky')()
  File "/usr/lib/python2.7/site-packages/finsky/cli.py", line 38, in main
    args.action(args)
  File "/usr/lib/python2.7/site-packages/finsky/cli.py", line 24, in download
    details = client.details(args.doc)
  File "/usr/lib/python2.7/site-packages/finsky/client.py", line 66, in details
    'X-DFE-No-Prefetch': 'true',
  File "/usr/lib/python2.7/site-packages/finsky/client.py", line 55, in request
    r.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://android.clients.google.com/fdfe/details?doc=com.snapchat.android

**Comment by mmcloughlin** [comment]
Closing this issue since I intend to archive this repository. It was an experimental project 10 years ago that I don't intend to work any more on.
